config/routes.rb
Flying::Application.routes.draw do
  

  devise_for :users

  resources :aircraft_types do
    member do
      get 'busca_aircraft_type'
    end
  end

  resources :clients do
    member do
      get 'retrieve_client_dac'
      get 'show_by_name'
      get 'id_by_name'
    end
    get 'pesquisa_nomes', :on => :collection
  end

  resources :instructors do
    member do
      get 'retrieve_instructor_dac'
      get 'show_by_name'
    end
    get 'search_names', :on => :collection

  end
  get "admins/manage_permission"
  get "admins/change_level"
  get "admins/new_user"
  post "admins/create_user"
  
  resources :sales

  resources :entries

  resources :suppliers do
    get 'show_by_name', :on => :member
    get 'id_by_name',   :on => :member
    get 'search_names', :on => :collection
  end

  root :to => 'flights#index'

  resources :debts

  resources :accounts do
    collection do
      get 'cash_flow'
    end
  end

  resources :flights do
    member do
      get 'load_aircraft_type_form'
      get 'print_notification'
    end
  end

  resources :packages do
    member do
      get 'busca_pacote'
    end
  end

  resources :aircrafts do
    member do
      get 'retrieve_aircraft_type_name'
    end
  end

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  belongs_to :aircraft_type
  has_many   :flights
  
  scope :starting_with, lambda { |i| where('prefix like (?)', i+'%')}

  def is_helicoptero?
    self.aircraft_type_id == AircratfType::HELICOPTERO
  end

  def is_autogyro?
    self.aircraft_type_id == AircratfType::AUTOGYRO
  end
  
  def is_ultraleve?
    self.aircraft_type_id = AircratfType::ULTRALEVE
  end
end

app/models/aircraft_type.rb
class AircraftType < ActiveRecord::Base
  
  has_many :aircrafts
  has_many :instructors
  
  scope :by_name, :order => :name
  
  HELICOPTERO = 1
  AUTOGYRO    = 2
  ULTRALEVE   = 3
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  
  before_filter :authenticate_user! 

  # GET /aircrafts
  # GET /aircrafts.json
  def index
    if params[:initials]
      @aircrafts = Aircraft.starting_with(params[:initials])
    else
      @aircrafts = Aircraft.all
    end
  end


  # GET /aircrafts/1
  # GET /aircrafts/1.json
  def show
    @aircraft = Aircraft.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @aircraft }
    end
  end

  # GET /aircrafts/new
  # GET /aircrafts/new.json
  def new
    @aircraft       = Aircraft.new
    @aircraft_types = AircraftType.by_name.collect{|at| [at.name, at.id]}
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @aircraft }
    end
  end

  # GET /aircrafts/1/edit
  def edit
    @aircraft       = Aircraft.find(params[:id])
    @aircraft_types = AircraftType.by_name.collect{|at| [at.name, at.id]}
  end

  # POST /aircrafts
  # POST /aircrafts.json
  def create
    @aircraft = Aircraft.new(params[:aircraft])

    respond_to do |format|
      if @aircraft.save
        format.html { redirect_to @aircraft, :notice => 'Aircraft was successfully created.' }
        format.json { render :json => @aircraft, :status => :created, :location => @aircraft }
      else
        @aircraft_types = AircraftType.by_name.collect{|at| [at.name, at.id]}

        format.html { render :action => "new" }
        format.json { render :json => @aircraft.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /aircrafts/1
  # PUT /aircrafts/1.json
  def update
    @aircraft = Aircraft.find(params[:id])

    respond_to do |format|
      if @aircraft.update_attributes(params[:aircraft])
        format.html { redirect_to @aircraft, :notice => 'Aircraft was successfully updated.' }
        format.json { head :ok }
      else
        @aircraft_types = AircraftType.by_name.collect{|at| [at.name, at.id]}

        format.html { render :action => "edit" }
        format.json { render :json => @aircraft.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /aircrafts/1
  # DELETE /aircrafts/1.json
  def destroy
    @aircraft = Aircraft.find(params[:id])
    @aircraft.destroy

    respond_to do |format|
      format.html { redirect_to aircrafts_url }
      format.json { head :ok }
    end
  end
  
  def retrieve_aircraft_type_name
    @aircraft = Aircraft.find(params[:id])
    render :json => @aircraft.aircraft_type.name.to_json
  end
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/views/aircrafts/_flights.html.erb
<div>
  <p><b>Flights</b></p>
  <table>
    <% @aircraft.flights.each do |fl| %>
      <tr>
        <td><%= fl.client.name %></td>
        <td><%= fl.flight_date %></td>
        <td><%= link_to fl.instructor.name, instructor_path(fl.instructor) %></td>
        <td><%= fl.duration %></td>
        <td><%= fl.aircraft.aircraft_type.name %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/aircrafts/_form.html.erb
<script type="text/javascript">
  $(function() {
		$(".datepicker").datepicker();
	});
</script>
<%= form_for(@aircraft) do |f| %>
  <% if @aircraft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aircraft.errors.count, "error") %> prohibited this aircraft from being saved:</h2>

      <ul>
      <% @aircraft.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Prefixo" %><br />
    <%= f.text_field :prefix %>
  </div>
  <div class="field">
    <%= f.label "Tipo" %><br />
    <%= f.select :aircraft_type_id, @aircraft_types %>
  </div>
  <div class="field">
    <%= f.label "Pertence à escola" %><br />
    <%= f.check_box :owner %>
  </div>
  <div class="field">
    <%= f.label "Fabricante" %><br />
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label "Modelo" %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label "Cores" %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label "Horímetro" %><br />
    <%= f.text_field :hourmeter %>
  </div>
  <div class="field">
    <%= f.label "Parada p/ manutenção" %><br />
	<%= f.text_field :maintenance_break, :class=>'datepicker', :size=>11 %>
  </div>
  <div class="field">
    <%= f.label "Última manutenção" %><br />
	<%= f.text_field :last_maintenance, :class=>'datepicker', :size=>11 %>
  </div>
  <div class="field">
    <%= f.label "Horas de vôo" %><br />
    <%= f.text_field :flyght_hours %>
  </div>
  <div class="field">
    <%= f.label  "Observações" %><br />
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label "Equipamento" %><br />
    <%= f.text_field :equipment %>
  </div>
  <div class="field">
    <%= f.label "Velocidade" %><br />
    <%= f.text_field :speed %>
  </div>
  <div class="field">
    <%= f.label "Operador" %><br />
    <%= f.text_field :operator %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aircrafts/edit.html.erb
<h1>Editar aeronave</h1>

<%= render 'form' %>


<%= link_to image_tag("left_arrow.png", :size=>"40x40", :border=>0, :title=>"Voltar"), aircrafts_path %>
<%= link_to image_tag("info.png", :size=>"40x40", :border=>0, :title=>"Detalhes"), @aircraft %>

app/views/aircrafts/index.html.erb
<table>
	<tr>
		<td><h1>Aeronaves</h1><td>
	<td><%= text_field_tag :name, params[:initials]%><%= submit_tag :search, :onclick => 'javascript:search();'%></td>
	</tr>
</table>
<hr>
<table width="90%">
  <tr>
    <th>Prefixo</th>
    <th>Tipo</th>
    <th>Fabricante</th>
    <th>Modelo</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>

<% @aircrafts.each do |aircraft| %>
  <tr>
    <td><%= link_to aircraft.prefix, aircraft %></td>
    <td><%= aircraft.aircraft_type.name %></td>
    <td><%= aircraft.manufacturer %></td>
    <td><%= aircraft.model %></td>
    <td><%= link_to "voo", new_flight_path(:aircraft_id => aircraft.id) %></td>
    <td align="right" width="25px"><%= link_to image_tag("info.png", :size=>"20x20", :border=>0, :title=>"Detalhes"), aircraft %></td>
    <td align="center" width="25px"><%= link_to image_tag("edit.png", :size=>"20x20", :border=>0, :title=>"Editar"), edit_aircraft_path(aircraft) %></td>
    <td align="left" width="25px"><%= link_to image_tag("trash.jpg",:size=>"20x20", :border=>0, :title=>"Excluir"), aircraft, :confirm => 'Tem certeza que quer excluir o registro?', :method => :delete %></td>
  </tr>


<% end %>

</table>
<br />
<hr>


<%= link_to image_tag("plus2.png", :size=>"40x40", :border=>0, :title=>"Adicionar"), new_aircraft_path %>

app/views/aircrafts/new.html.erb
<h1>Adicionar Aeronave</h1>

<%= render 'form' %>

<%= link_to image_tag("left_arrow.png", :size=>"40x40", :border=>0, :title=>"Voltar"), aircrafts_path %>

app/views/aircrafts/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Detalhes da Aeronave</h1>
<hr>
<table class="table" id="table_form" cellspacing="0" cellpadding="0">
	<tr class="rowa">
		<td class="col1 cell"><b>Prefixo:</b> <%= @aircraft.prefix %></td>
		<td class="col2 cell"><b>Tipo:</b> <%= @aircraft.aircraft_type.name %> </td>
		<td class="col3 cell"><b>Pertence à escola:</b> <%= @aircraft.owner %></td>
	</tr>
 	<tr class="rowa">
		<td class="col1 cell"><b>Fabricante:</b> <%= @aircraft.manufacturer %></td>
		<td class="col2 cell"><b>Modelo:</b> <%= @aircraft.model %> </td>
		<td class="col3 cell"><b>Cor:</b> <%= @aircraft.color %>  </td>
	</tr>
 	<tr class="rowa">
		<td class="col1 cell"><b>Horímetro:</b> <%= @aircraft.hourmeter %> </td>
		<td class="col2 cell"><b>Parada p/ manutenção:</b> <%= @aircraft.maintenance_break %></td>
		<td class="col3 cell"><b>Última manutenção:</b> <%= @aircraft.last_maintenance %> </td>
	</tr>
 	<tr class="rowa">
		<td class="col1 cell"><b>Horas de vôo:</b> <%= @aircraft.flyght_hours %> </td>
		<td class="col2 cell"><b>Detalhes:</b> <%= @aircraft.details %> </td>
		<td class="col3 cell"><b>Equipamento:</b> <%= @aircraft.equipment %> </td>
	</tr>
 	<tr class="rowa">
		<td class="col1 cell"><b>Velocidade:</b> <%= @aircraft.speed %> </td>
		<td class="col2 cell"><b>Operador:</b> <%= @aircraft.operator %> </td>
		<td class="col3 cell"> </td>
	</tr>
 </table>
<hr> 
<%= render :partial => 'flights'%>
<hr>
<%= link_to image_tag("left_arrow.png", :size=>"40x40", :border=>0, :title=>"Voltar"), aircrafts_path %>
<%= link_to image_tag("edit.png", :size=>"40x40", :border=>0, :title=>"Editar"), edit_aircraft_path(@aircraft) %>