config/routes.rb
Flying::Application.routes.draw do
  

  devise_for :users

  resources :aircraft_types do
    member do
      get 'busca_aircraft_type'
    end
  end

  resources :clients do
    member do
      get 'retrieve_client_dac'
      get 'show_by_name'
      get 'id_by_name'
    end
    get 'pesquisa_nomes', :on => :collection
  end

  resources :instructors do
    member do
      get 'retrieve_instructor_dac'
      get 'show_by_name'
    end
    get 'search_names', :on => :collection

  end
  get "admins/manage_permission"
  get "admins/change_level"
  get "admins/new_user"
  post "admins/create_user"
  
  resources :sales

  resources :entries

  resources :suppliers do
    get 'show_by_name', :on => :member
    get 'id_by_name',   :on => :member
    get 'search_names', :on => :collection
  end

  root :to => 'flights#index'

  resources :debts

  resources :accounts do
    collection do
      get 'cash_flow'
    end
  end

  resources :flights do
    member do
      get 'load_aircraft_type_form'
      get 'print_notification'
    end
  end

  resources :packages do
    member do
      get 'busca_pacote'
    end
  end

  resources :aircrafts do
    member do
      get 'retrieve_aircraft_type_name'
    end
  end

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :flights
  # belongs_to :aircraft_type
  
  validates_numericality_of :hour_price, :on => [:create, :update], :message => "is not a number"
  validates_presence_of :hour_price, :on => :create, :message => "can't be blank"
  # validates_presence_of :aircraft_type_id
  
  scope :starting_with, lambda { |i| where('name like (?)', i+'%')}
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  before_filter :authenticate_user! 

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all(:order => :name)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @instructors }
    end
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
    @instructor = Instructor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @instructor }
    end
  end
  def retrieve_instructor_dac
    @instructor = Instructor.find(params[:id])
    render :json => @instructor.instructor_dac.to_json
  end
  # GET /instructors/new
  # GET /instructors/new.json
  def new
    @instructor     = Instructor.new
    @aircraft_types = AircraftType.by_name.collect{|at| [at.name, at.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @instructor }
    end
  end

  # GET /instructors/1/edit
  def edit
    @instructor     = Instructor.find(params[:id])
    @aircraft_types = AircraftType.by_name.collect{|at| [at.name, at.id]}
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(params[:instructor])

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, :notice => 'Instructor was successfully created.' }
        format.json { render :json => @instructor, :status => :created, :location => @instructor }
      else
        @aircraft_types = AircraftType.by_name.collect{|at| [at.name, at.id]}

        format.html { render :action => "new" }
        format.json { render :json => @instructor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /instructors/1
  # PUT /instructors/1.json
  def update
    @instructor = Instructor.find(params[:id])

    respond_to do |format|
      if @instructor.update_attributes(params[:instructor])
        format.html { redirect_to @instructor, :notice => 'Instructor was successfully updated.' }
        format.json { head :ok }
      else
        @aircraft_types = AircraftType.by_name.collect{|at| [at.name, at.id]}

        format.html { render :action => "edit" }
        format.json { render :json => @instructor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy

    respond_to do |format|
      format.html { redirect_to instructors_url }
      format.json { head :ok }
    end
  end

  def search_names
    result = Instructor.all(:conditions=>["name like ?", params[:term] + '%'],
                        :select => 'name')
    render :json => result.map(&:name).to_json
  end
  
  def show_by_name
    @instructor = Instructor.find_by_name(params[:id])
    render 'show'
  end

end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_flights.html.erb
<div>
  <p><b>Vôos</b></p>
  <table>
	<tr>
		<th>Aeronave</th>
		<th>Data</th>
		<th>Hora</th>
		<th>Cliente</th>		
		<th>Duração</th>
	</tr>
    <% @instructor.flights.each do |fl| %>
      <tr>
        <td><%= link_to fl.aircraft.prefix, aircraft_path(fl.aircraft) %></td>
        <td><%= fl.flight_date %></td>
        <td><%= fl.flight_time_br %></td>
        <td><%= fl.client.name %></td>
        <td><%= fl.duration %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <!-- <div class="field">
    <%= f.label 'Tipo de aeronave' %><br />
    <%= f.select :aircraft_type_id, @aircraft_types  %>
  </div> -->
  <div class="field">
    <%= f.label :level %><br />
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :rg %><br />
    <%= f.text_field :rg %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :instructor_dac %><br />
    <%= f.text_field :instructor_dac %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday, :start_year => 1920 %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :cel %><br />
    <%= f.text_field :cel %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :hour_price %><br />
    <%= f.text_field :hour_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editar Instrutor</h1>

<%= render 'form' %>


<%= link_to image_tag("left_arrow.png", :size=>"40x40", :border=>0, :title=>"Voltar"), instructors_path %>
<%= link_to image_tag("info.png", :size=>"40x40", :border=>0, :title=>"Detalhes"), @instructor%>

app/views/instructors/index.html.erb
<style type='text/css'>
    .ui-autocomplete {
      max-height: 180px;
      overflow-y: auto;
    }
</style>
<script type="text/javascript">
  $(function() {
    
      function retrieve_instructor(name){
        window.location = "/instructors/"+ name + "/show_by_name/";
      }
      
      $("#name").autocomplete({
        source: "instructors/search_names",
        minLength: 2,
        maxRows: 7,
        select: function(event,ui){
          name = ui.item.value;
          retrieve_instructor(name);
          return false;
        },
        focus: function(e,ui){
          return false;
        },
      });

  });
</script>
<table>
	<tr>
		<td><h1>Instrutores</h1><td>
	<td>Pesquisa por nome : <%= text_field_tag :name, params[:initials] , :class => 'autocomplete' %></td>
	</tr>
</table>

<table>
  <tr>
    <th>Nome</th>
    <th>Nível</th>
    <th>Data de nascimento</th>
    <th>Telefone</th>
    <th>Celular</th>
    <th>Email</th>
    <th>Valor hora</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instructors.each do |instructor| %>


<tr>
    <td><%= link_to instructor.name, instructor %></td>
    <td><%= instructor.level %></td>
    <td><%= instructor.birthday.to_s_br %></td>
    <td><%= instructor.phone %></td>
    <td><%= instructor.cel %></td>
    <td><%= instructor.email %></td>
    <td><%= instructor.hour_price.real %></td>
    <td align="right"><%= link_to image_tag("info.png", :size=>"20x20", :border=>0, :title=>"Detalhes"), instructor %></td>
    <td align="center"><%= link_to image_tag("edit.png", :size=>"20x20", :border=>0, :title=>"Editar"), edit_instructor_path(instructor) %></td>
    <td align="left"><%= link_to image_tag("trash.jpg",:size=>"20x20", :border=>0, :title=>"Excluir"), instructor, :confirm => 'Tem certeza que quer excluir o registro?', :method => :delete %></td>


  </tr>

<% end %>

<hr>

</table>

<br />
<hr>
<%= link_to image_tag("plus2.png", :size=>"40x40", :border=>0, :title=>"Adicionar"), new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New instructor</h1>

<%= render 'form' %>

<%= link_to image_tag("left_arrow.png", :size=>"40x40", :border=>0, :title=>"Voltar"), instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Detalhes do Instrutor</h1>
<hr>
<p>
  <b>Nome:</b>
  <%= @instructor.name %>
</p>

<p>
  <b>Nível:</b>
  <%= @instructor.level %>
</p>

<p>
  <b>Identidade:</b>
  <%= @instructor.rg %>
</p>

<p>
  <b>CPF:</b>
  <%= @instructor.cpf %>
</p>

<p>
  <b>DAC Instrutor:</b>
  <%= @instructor.instructor_dac %>
</p>

<p>
  <b>Data de nascimento:</b>
  <%= @instructor.birthday %>
</p>

<p>
  <b>Endereço:</b>
  <%= @instructor.address %>
</p>

<p>
  <b>Telefone:</b>
  <%= @instructor.phone %>
</p>

<p>
  <b>Celular:</b>
  <%= @instructor.cel %>
</p>

<p>
  <b>Email:</b>
  <%= @instructor.email %>
</p>

<p>
  <b>Valor hora:</b>
  <%= @instructor.hour_price %>
</p>

<hr>
<%= render :partial => 'flights'%>
<hr>
<%= link_to image_tag("left_arrow.png", :size=>"40x40", :border=>0, :title=>"Voltar"), instructors_path %>
<%= link_to image_tag("edit.png", :size=>"40x40", :border=>0, :title=>"Editar"), edit_instructor_path(@instructor) %>