config/routes.rb
Flying::Application.routes.draw do
  

  devise_for :users

  resources :aircraft_types do
    member do
      get 'busca_aircraft_type'
    end
  end

  resources :clients do
    member do
      get 'retrieve_client_dac'
      get 'show_by_name'
      get 'id_by_name'
    end
    get 'pesquisa_nomes', :on => :collection
  end

  resources :instructors do
    member do
      get 'retrieve_instructor_dac'
      get 'show_by_name'
    end
    get 'search_names', :on => :collection

  end
  get "admins/manage_permission"
  get "admins/change_level"
  get "admins/new_user"
  post "admins/create_user"
  
  resources :sales

  resources :entries

  resources :suppliers do
    get 'show_by_name', :on => :member
    get 'id_by_name',   :on => :member
    get 'search_names', :on => :collection
  end

  root :to => 'flights#index'

  resources :debts

  resources :accounts do
    collection do
      get 'cash_flow'
    end
  end

  resources :flights do
    member do
      get 'load_aircraft_type_form'
      get 'print_notification'
    end
  end

  resources :packages do
    member do
      get 'busca_pacote'
    end
  end

  resources :aircrafts do
    member do
      get 'retrieve_aircraft_type_name'
    end
  end

end

app/models/sale.rb
class Sale < ActiveRecord::Base

  belongs_to :client
  belongs_to :aircraft_type
  
  validates_presence_of :client_id, :date, :hours_br

  scope :between_date, lambda {|start_date,end_date| 
                    where("date between  ? and  ? ", start_date, end_date)}
  scope :by_client, lambda{|id| where("client_id = ? ", id)}                
  
  after_save :create_balance
  
  attr_accessor :date_br, :hours_br
  
  def date_br
    if Date.valid?(self.date)
      self.date.to_s_br
    else
      Date.today.to_s_br
    end
  end
  
  def date_br=(val)
    self.date = val.to_date rescue nil
  end
 
  def hours_br
    self.hours.to_s.sub(".", ",")
  end
  
  def hours_br=(new_value)
    self.hours = new_value.gsub(",", ".").to_d  if new_value.present?
  end
  
  def total_value
    result = (self.hours * self.value)
    result += result - self.discount if self.discount
    result
  end
  
  def create_balance
    balance = Balance.find_by_sale_id(self.id)
    balance.destroy if balance

    Balance.create(:client_id    => self.client_id,
                   :sale_id      => self.id,
                   :date         => self.date,
                   :hours        => self.hours,
                   :aircraft_type_id => self.aircraft_type.id)
  end
  
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  
  before_filter :authenticate_user! 
  # GET /sales
  # GET /sales.json
  def index
    date_params
    @sales = Sale.between_date(@start_date.to_date, @end_date.to_date).order(:date)
    if params[:client_id] && params[:client_id].to_i > 0
      @sales = @sales.by_client(params[:client_id])
      params[:initials] = Client.find( params[:client_id]).name
    end
    @clients     = Client.all.collect{ |c| [c.name, c.id] }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale = Sale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @sale }
    end
  end

  # GET /sales/new
  # GET /sales/new.json
  def new
    @sale      = Sale.new(:date=>Date.today)
    @clients   = Client.all(:order=>:name).collect{|c| [c.name, c.id]}
    @aircraft_types = AircraftType.all(:order=>:name).collect{|c| [c.name, c.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @sale }
    end
  end

  # GET /sales/1/edit
  def edit
    @sale     = Sale.find(params[:id])
    @clients  = Client.all(:order=>:name).collect{|c| [c.name, c.id]}
    @aircraft_types = AircraftType.all(:order=>:name).collect{|c| [c.name, c.id]}

  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(params[:sale])

    respond_to do |format|
      if @sale.save
        # format.html { redirect_to @sale, :notice => 'Sale was successfully created.' }
        format.json { render :json => @sale, :status => :created, :location => @sale }
        format.html {redirect_to new_entry_path(
                        :client_id=> @sale.client_id, 
                        :date => @sale.date, 
                        :value => @sale.total_value , 
                        :description=>@sale.aircraft_type.name)}
      else
        @clients   = Client.all(:order=>:name).collect{|c| [c.name, c.id]}
        @aircraft_types = AircraftType.all(:order=>:name).collect{|c| [c.name, c.id]}
        
        format.html { render :action => "new" }
        format.json { render :json => @sale.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sales/1
  # PUT /sales/1.json
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to @sale, :notice => 'Sale was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @sale.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale    = Sale.find(params[:id])
    @balance = Balance.find_by_sale_id(@sale.id)
    @sale.destroy
    @balance.destroy

    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<script type='text/javascript'>
  $(function() {
    $("#sale_aircraft_type_id").change(function(){
      retrieve_aircraft_type();
    });
    retrieve_aircraft_type();
  });
  
  function retrieve_aircraft_type(){
    $.ajax({
        url: '/aircraft_types/' + $("#sale_aircraft_type_id").val() + '/busca_aircraft_type',
        type: 'GET',
        // data: { id: $("#sale_aircraft_type_id").val() },
        success: function(data){
          $("#value").html(data.hour_price);
          // $("#hours").html(data.quantity);
          $("#sale_value").val(data.hour_price);
          // $("#sale_hours").val(data.quantity);
          calculate_total_sale();
        }
      });
  }


</script>


<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label "Cliente" %><br />
      <%= f.select :client_id , @clients, :prompt => 'Selecione'%>
    </div>

    <div class="field">
      <%= f.label "Tipo de aeronave" %><br />
      <%= f.select :aircraft_type_id, @aircraft_types %>
    </div>
    
    <div class="field">
      <%= f.label "Valor Hora" %><br />
      <span id="value"></span>
      <%= f.hidden_field :value %>
    </div>

    <div class='field'> 
      <%= f.label "Horas" %><br />
      <span id="hours"></span>
      <%= f.text_field :hours_br , :size=>5, :onblur => 'javascript:calculate_total_sale();' %>
      <span id="total_value"></span>
    </div>
    
    <div class="field">
      <%= f.label :Data %><br />
      <%= f.text_field :date_br, :class=>'datepicker', :size=>11 %>
    </div>

    <div class='field'> 
      <%= f.label "Descrição" %><br />
      <%= f.text_field :description %>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editar Venda</h1>
<hr>
<%= render 'form' %>
<hr>
<%= link_to image_tag("left_arrow.png", :size=>"40x40", :border=>0, :title=>"Voltar"), sales_path %>
<%= link_to image_tag("info.png", :size=>"40x40", :border=>0, :title=>"Detalhes"), @sale%>

app/views/sales/index.html.erb
<style type='text/css'>
    .ui-autocomplete {
      max-height: 180px;
      overflow-y: auto;
    }
</style>
<script type="text/javascript">
  $(function() {
    
      function retrieve_client_id(name){
        $.ajax({
          url: '/clients/' + name + '/id_by_name',
          type: 'GET',
          success: function(id){
            $("#client_id").val(id);
            $("#name").val(name);
            $("#submit").focus();
          }
        });
      }
      
      $("#name").autocomplete({
        source: "clients/pesquisa_nomes",
        minLength: 2,
        maxRows: 7,
        select: function(event,ui){
          name = ui.item.value;
          retrieve_client_id(name);
          return false;
        },
        focus: function(e,ui){
          $("#client_id").val("");
          return false;
        },
      });

  });
</script>

<h1>Vendas</h1>
<table>
	<tr>
		<th>Cliente:</th>
		<th>Data:</th>
	</tr>
	 	<td><%= text_field_tag :name, params[:initials] , :class => 'autocomplete' %><%= hidden_field_tag :client_id %></td>
    <td><%= render :partial => '/shared/date_range' %></td>
	</tr>
</table>
<hr>

<table>
  <tr>
    <th>Data</th>
    <th>Cliente</th>
    <th>Tipo de aeronave</th>
    <th align='right'>Valor hora</th>
    <th align='right'>quantidade</th>
    <th align='right'>Valor total</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>

<% @sales.each do |sale| %>
  <tr>
    <td><%= sale.date_br %></td>
    <td><%= link_to sale.client.name, client_path(sale.client) %></td>
    <td><%= sale.aircraft_type.name %></td>
    <td align='right'><%= sale.value.real %></td>
    <td align='right'><%= sale.hours %></td>
    <td align="right"><%= sale.total_value.real %></td>
    <td align="right"><%= link_to image_tag("info.png", :size=>"20x20", :border=>0, :title=>"Detalhes"), sale %></td>
    <td align="center"><%= link_to image_tag("edit.png", :size=>"20x20", :border=>0, :title=>"Editar"), edit_sale_path(sale) %></td>
    <td align="left"><%= link_to image_tag("trash.jpg",:size=>"20x20", :border=>0, :title=>"Excluir"), sale, :confirm => 'Tem certeza que quer excluir o registro?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<hr>
<%= link_to image_tag("plus2.png", :size=>"40x40", :border=>0, :title=>"Adicionar"), new_sale_path %>

app/views/sales/new.html.erb
<h1>Adicionar Venda</h1>
<hr>
<%= render 'form' %>
<hr>
<%= link_to image_tag("left_arrow.png", :size=>"40x40", :border=>0, :title=>"Voltar"), sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>