config/routes.rb
Flying::Application.routes.draw do
  

  devise_for :users

  resources :aircraft_types do
    member do
      get 'busca_aircraft_type'
    end
  end

  resources :clients do
    member do
      get 'retrieve_client_dac'
      get 'show_by_name'
      get 'id_by_name'
    end
    get 'pesquisa_nomes', :on => :collection
  end

  resources :instructors do
    member do
      get 'retrieve_instructor_dac'
      get 'show_by_name'
    end
    get 'search_names', :on => :collection

  end
  get "admins/manage_permission"
  get "admins/change_level"
  get "admins/new_user"
  post "admins/create_user"
  
  resources :sales

  resources :entries

  resources :suppliers do
    get 'show_by_name', :on => :member
    get 'id_by_name',   :on => :member
    get 'search_names', :on => :collection
  end

  root :to => 'flights#index'

  resources :debts

  resources :accounts do
    collection do
      get 'cash_flow'
    end
  end

  resources :flights do
    member do
      get 'load_aircraft_type_form'
      get 'print_notification'
    end
  end

  resources :packages do
    member do
      get 'busca_pacote'
    end
  end

  resources :aircrafts do
    member do
      get 'retrieve_aircraft_type_name'
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  
  belongs_to :supplier
  belongs_to :company, :class_name => 'AircraftType' 
    
  validates_numericality_of :value, :on => [:create, :update], :message => "is not a number"
  validates_presence_of :value, :on => [:create, :update], :message => "can't be blank"
  
  scope :between_due_dates, lambda {|start_date,end_date| 
                    where("due_date between  ? and  ? ", start_date, end_date)
                  }
  scope :between_payment_dates, lambda {|start_date,end_date| 
                    where("payment_date between  ? and  ? ", start_date, end_date)
                  }
  scope :by_company, lambda{|id| where("company_id = ? ", id)}  
  scope :by_supplier, lambda{|id| where("supplier_id = ? ", id)}  
  scope :confirmed, lambda {|payed| where('payed=?' , payed)}
  scope :not_payed, where(:payed=>false)
  
  attr_accessor :payment_date_br, :due_date_br

  def payment_date_br
    if Date.valid?(self.payment_date)
      self.payment_date.to_s_br
    else
      ''
    end
  end
  def payment_date_br=(val)
    self.payment_date = val.to_date rescue nil
  end
  
  def due_date_br
    if Date.valid?(self.due_date)
      self.due_date.to_s_br
    else
      Date.today.to_s_br
    end
  end
  def due_date_br=(val)
    self.due_date = val.to_date rescue nil
  end
  
  def to_label
    "#{client_id} (#{company_id})"
  end
  

  def due_date
    self.payment_date
  end
    
  def total
    result = self.value
    result += self.interest if self.interest
    result -= self.discount if self.discount
    result
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  
  before_filter :authenticate_user! 
  
  # GET /accounts
  # GET /accounts.json
  def index

    @suppliers  = Supplier.all.collect{ |s| [s.name, s.id] }
    @aircraft_types   = AircraftType.all(:order => :name).collect{|c| [c.name, c.id]}

    date_params
    if params[:date_option] == 'due_date'
      @payments   = Account.between_due_dates(@start_date.to_date, @end_date.to_date).order(:due_date)
    else
      @payments   = Account.between_payment_dates(@start_date.to_date, @end_date.to_date).order(:payment_date)
    end

      debugger
    if params[:supplier_id] && params[:supplier_id].to_i > 0
      @payments = @payments.by_supplier(params[:supplier_id])
      params[:initials] = Supplier.find(params[:supplier_id]).name
    end
    if params[:aircraft_type_id] && params[:aircraft_type_id].to_i > 0
      @payments = @payments.by_company(params[:aircraft_type_id])
    end
    
    @payments = @payments.payed if params[:confirmed] == 'sim'
    @payments = @payments.not_payed if params[:confirmed] == 'não'
    @titulo = "Pagamentos entre #{@start_date} e #{@end_date}"

    @payed_total = 0
    @payments.each do |pay|
      @payed_total += pay.value
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account          = Account.new()
    @account.due_date = Date.today
    @suppliers        = Supplier.all(:order=>:name).collect{|c| [c.name, c.id]}
    @aircraft_types   = AircraftType.all(:order => :name).collect{|c| [c.name, c.id]}

    # @packages  = Package.actives.collect{|c| [c.name, c.id]}
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account   = Account.find(params[:id])
    @suppliers = Supplier.all(:order=>:name).collect{|c| [c.name, c.id]}
    @aircraft_types   = AircraftType.all(:order => :name).collect{|c| [c.name, c.id]}
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])
    @account.description = params[:account][:description]
    @account.value = params[:account][:value]

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, :notice => 'Account was successfully created.' }
        format.json { render :json => @account, :status => :created, :location => @account }
      else
        @suppliers        = Supplier.all(:order=>:name).collect{|c| [c.name, c.id]}
        @aircraft_types   = AircraftType.all(:order => :name).collect{|c| [c.name, c.id]}

        format.html { render :action => "new" }
        format.json { render :json => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, :notice => 'Account was successfully updated.' }
        format.json { head :ok }
      else
        @suppliers        = Supplier.all(:order=>:name).collect{|c| [c.name, c.id]}
        @aircraft_types   = AircraftType.all(:order => :name).collect{|c| [c.name, c.id]}

        format.html { render :action => "edit" }
        format.json { render :json => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :ok }
    end
  end
  
  
  def cash_flow
    date_params
    @entries    = Entry.between_due_dates(@start_date.to_date, @end_date.to_date).confirmed(false)
    @payments   = Account.between_due_dates(@start_date.to_date, @end_date.to_date).order(:due_date).confirmed(false) || []
    @clients    = Client.all.collect{ |c| [c.name, c.id] }
    @suppliers  = Supplier.all.collect{ |s| [s.name, s.id] }
    @titulo = "Fluxo de caixa entre #{@start_date} e #{@end_date}"


    @entry_total = 0
    @entries.each do |entry|
      @entry_total += entry.total
    end
    @payed_total = 0
    if @payments
      @payments.each do |pay|
        @payed_total += pay.total if pay.value
      end
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @accounts }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_cash_flow.html.erb
<table width="90%">
  <tr>
    <th>Data prevista</th>
    <th>Data efetiva</th>
    <th>Confirmado</th>
    <th>Cliente/Fornecedor</th>
    <th>Descritivo</th>
    <th align='right'>Débito</th>
    <th align='right'>Crédito</th>
    <th align='right'>Saldo</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>

  </tr>

<% credit = 0 %>
<% debit  = 0 %>
<% data.each do |entry| %>
  <tr>
    <% if entry.is_a? Entry %>
      <td><%= entry.due_date_br %></td>
      <td><%= entry.entry_date_br %></td>
      <td><%= entry.received? ? 'sim' : 'não'%></td>
      <td><%= entry.client && entry.client.name %></td>
      <td><%= entry.description %></td>
      <td>&nbsp;</td>
      <td align='right'><%= entry.total.real %></td>
      <% credit += entry.total %>
    <% else %>
      <td><%= entry.due_date_br %></td>
      <td><%= entry.payment_date_br %></td>
      <td><%= entry.payed? ? 'sim' : 'não' %></td>
      <td><%= entry.supplier && entry.supplier.name %></td>
      <td><%= entry.description %></td>
      <td align='right'><%= entry.total.real %></td>
      <td>&nbsp;</td>
      <% debit += entry.total %>
    <% end %>
    <td align='right'><%= (credit - debit).real %></td>
    <td align="right" width="25px"><%= link_to image_tag("info.png", :size=>"20x20", :border=>0, :title=>"Detalhes"), entry %></td>
    <td align="center" width="25px">
      <%= link_to image_tag("edit.png", :size=>"20x20", :border=>0, :title=>"Editar"), entry.is_a?(Entry) ? edit_entry_path(entry) : edit_account_path(entry) %>
    </td>
    <td align="left" width="25px"><%= link_to image_tag("trash.jpg",:size=>"20x20", :border=>0, :title=>"Excluir"), entry, :confirm => 'Tem certeza que quer excluir o registro?', :method => :delete %></td>
  </tr>
<% end %>

<tr>

  <td colspan="4" align="center"><b>Total</b></td>
  <td align='right'><b><%= debit.real %></b></td>
  <td align='right'><b><%= credit.real %></b></td>
  <td>&nbsp;</td>

</tr>
<hr>
</table>
<hr>
<br />

app/views/accounts/_entries.html.erb
<hr>
<h1>Recebimentos</h1>
<table width="90%" border='0'>
  <tr>
    <th><%= confirmed ? "Recebido em" : "A receber em"%></th>
    <th>Cliente</th>
    <th>Descritivo</th>
    <th align='right'>Valor</th>
    <th>Centro de custo</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>

<% data.each do |entry| %>
  <tr>
      <td><%= confirmed ? entry.entry_date_br : entry.due_date_br %></td>
      <td><%= entry.client && entry.client.name %></td>
      <td><%= entry.description %></td>
      <td align='right'><%= entry.total.real %></td>
      <td><%= entry.aircraft_type.name if entry.aircraft_type %></td>
    <td align="right" width="25px"><%= link_to image_tag("info.png", :size=>"20x20", :border=>0, :title=>"Detalhes"), entry %></td>
    <td align="center" width="25px"><%= link_to image_tag("edit.png", :size=>"20x20", :border=>0, :title=>"Editar"), edit_entry_path(entry) %></td>
    <td align="left" width="25px"><%= link_to image_tag("trash.jpg",:size=>"20x20", :border=>0, :title=>"Excluir"), entry, :confirm => 'Tem certeza que quer excluir o registro?', :method => :delete %></td>
  </tr>
<% end %>
<tr>
  <td colspan="3" align="right">&nbsp;</td>
  <td align='right'>--------</td>
</tr>
<tr>
  <td colspan="3" align="right"><b>Total</b></td>
  <td align='right'><b><%= @entry_total.real %></b></td>
</tr>
</table>
<br />
<hr>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label "Fornecedor" %><br />
      <%= f.select :supplier_id , @suppliers %>
    </div>
    <div class="field">
      <%= f.label "Centro de custo" %><br />
      <%= f.select :company_id , @aircraft_types, :include_blank => true %>
    </div>
    <div class="field">
      <%= f.label "Vencimento" %><br />
      <%= f.text_field :due_date_br, :class=>'datepicker', :size => 9 %>
    </div>

    <div class="field">
      <%= f.label :value %><br />
      <%= f.text_field :value, :size => 9 %>
    </div>

    <div class="field">
      <%= f.label 'Juros' %><br />
      <%= f.text_field :interest, :size => 9 %>
    </div>

    <div class="field">
      <%= f.label 'Desconto' %><br />
      <%= f.text_field :discount, :size => 9 %>
    </div>

    <div class="field">
      <%= f.label 'Código de barras' %><br />
      <%= f.text_field :barcode, :size => 49 %>
    </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows=>3 %>
  </div>
  
  <div>
    <%= f.check_box :payed , :disabled => !@account.new_record? && !current_user.master? %>
    <%= f.label "Pago em "%>
    <%= f.text_field :payment_date_br, :class=>'datepicker', :size => 9 %>  </div>

<br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<hr>

app/views/accounts/_payments.html.erb
<table>
  <tr>
    <th><%= confirmed ? "Pago em" : "A pagar em"%></th>
    <th>Fornecedor</th>
    <th>Descritivo</th>
    <th align='right'>Valor</th>
    <th>Centro de custo</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>
<% total = 0%>
<% data.each do |account| %>
  <tr>
    <td><%= confirmed ? account.payment_date_br : account.due_date_br %></td>
    <td><%= account.supplier && account.supplier.name %></td>
    <td><%= account.description %></td>
    <td align='right'><%= account.value.real %></td>
    <% total += account.total if account.total %>
    <td><%= account.company.name if account.company %></td>
    <td align="right" width="25px"><%= link_to image_tag("info.png", :size=>"20x20", :border=>0, :title=>"Detalhes"), account, :class=>"index_link" %></td>
    <td align="center" width="25px"><%= link_to image_tag("edit.png", :size=>"20x20", :border=>0, :title=>"Editar"), edit_account_path(account) , :class=>"index_link" %></td>
    <td align="left" width="25px"><%= link_to image_tag("trash.jpg",:size=>"20x20", :border=>0, :title=>"Excluir"), account, :confirm => 'Tem certeza que quer excluir o registro?', :method => :delete, :class=>"index_link" if current_user.master? %></td>

  </tr>
<% end %>
<tr>
  <td colspan="3" align="right">&nbsp;</td>
  <td align='right'>--------</td>
</tr>

<tr>
  <td colspan="3" align="right"><b>Total</b></td>
  <td align='right'><b><%= @payed_total.real %></b></td>
</tr>

</table>

app/views/accounts/_sales.html.erb
<hr>
<h1>Recebimentos</h1>
<%= @data %>
<table width="90%">
  <tr>
    <th>Cliente</th>
    <th>Tipo</th>
    <th>Empresa</th>
    <th>Vencimento</th>
    <th>Descritivo</th>
    <th>Valor</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% data.each do |receive| %>
  <tr>
    <td><%= receive.date %></td>
    <td><%= receive.client && receive.client.name %></td>
    <td><%= receive.description %></td>
    <td><%= receive.value %></td>
    <td align="right" width="25px"><%= link_to image_tag("info.png", :size=>"20x20", :border=>0, :title=>"Detalhes"), receive %></td>
    <td align="center" width="25px"><%= link_to image_tag("edit.png", :size=>"20x20", :border=>0, :title=>"Editar"), edit_entry_path(receive) %></td>
    <td align="left" width="25px"><%= link_to image_tag("trash.jpg",:size=>"20x20", :border=>0, :title=>"Excluir"), receive, :confirm => 'Tem certeza que quer excluir o registro?', :method => :delete %></td>
  </tr>
<% end %>

</table>

<br />

<%= link_to image_tag("plus2.png", :size=>"40x40", :border=>0, :title=>"Adicionar"), new_entry_path %>

app/views/accounts/cash_flow.html.erb
<div id="title">
  <h1><%= params[:confirmed]=='true' ?  'Fluxo de Caixa' : 'Previsão de Caixa' %></h1>
</div>
<%= hidden_field_tag :confirmed, params[:confirmed] %>
<table>
	<tr>
		<th>Inicial:</th>
		<th>Final:</th>
	</tr>
	<tr>
		<%= render :partial => '/shared/date_range' %>
	</tr>
</table>
<div id="printable-part">
  <span id="print-title"></span>

  <%= render :partial => 'entries' , :locals => {:data => @entries,
                 :confirmed => params[:confirmed]=='true' } %>

  <h1>Pagamentos</h1>
  <%= render :partial => 'payments' , :locals => {:data => @payments,
                 :confirmed => params[:confirmed]=='true' } %>
</div>
<hr> 
<%= link_to image_tag("printer.png", :size=>"40x40", :border=>0, :title=>"Imprimir relatório"), "javascript:print('#{@titulo}');"%>

<div id="dialog" title="Basic dialog"></div>

app/views/accounts/edit.html.erb
<h1>Editar</h1>

<%= render 'form' %>

<%= link_to image_tag("left_arrow.png", :size=>"40x40", :border=>0, :title=>"Voltar"), accounts_path %>
<%= link_to image_tag("info.png", :size=>"40x40", :border=>0, :title=>"Detalhes"), @account%>

app/views/accounts/index.html.erb
<style type='text/css'>
    .ui-autocomplete {
      max-height: 180px;
      overflow-y: auto;
    }
</style>
<script type="text/javascript">
  $(function() {
    
      function retrieve_supplier_id(name){
        $.ajax({
          url: '/suppliers/' + name + '/id_by_name',
          type: 'GET',
          success: function(id){
            $("#supplier_id").val(id);
            $("#name").val(name);
            $("#submit").focus();
          }
        });
      }
      
      $("#name").autocomplete({
        source: "suppliers/search_names",
        minLength: 2,
        maxRows: 7,
        select: function(event,ui){
          name = ui.item.value;
          retrieve_supplier_id(name);
          return false;
        },
        focus: function(e,ui){
          $("#supplier_id").val("");
          return false;
        },
      });

  });
</script>
<div id="title">
  <h1>Pagamentos</h1>
</div>
<table>
	<tr>
	  <th>Centro de custo</th>
		<th>Fornecedor:</th>
		<th>Pago:</th>
		<th>Inicial:</th>
		<th>Final:</th>
	</tr>
	<tr>
	  <td><%= select_tag :company_id, options_for_select(@aircraft_types, params[:aircraft_type_id]), :prompt => 'Selecione'  %></td>
		<td vertical-align="top"><%= text_field_tag :name, params[:initials] , :class => 'autocomplete' %><%= hidden_field_tag :supplier_id %></td>
    <td><%= select_tag :confirmed, options_for_select([['ambos'],['Sim'], ['Não']], params[:confirmed]) %></td>

		<%= render :partial => '/shared/date_range' %>
	</tr>
</table>
 <div id="printable-part">
    <span id="print-title"></span>
<%= render :partial => 'payments' , :locals => {:data => @payments,
               :confirmed => params[:confirmed]=='true'}  %>
</div>              
			<hr>
               
<%= link_to image_tag("plus2.png", :size=>"40x40", :border=>0, :title=>"Adicionar"), new_account_path %>

<%= link_to image_tag("printer.png", :size=>"40x40", :border=>0, :title=>"Imprimir relatório"), "javascript:print('#{@titulo}');"%>

<div id="dialog" title="Basic dialog"></div>

app/views/accounts/new.html.erb
<h1>Adicionar Pagamento %></h1>
<hr>

<%= render 'form' %>

<%= link_to image_tag("left_arrow.png", :size=>"40x40", :border=>0, :title=>"Voltar"), accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <p>
  <b>Tipo:</b>
  <%= @account.type %>
</p>

<p>
  <b>Empresa:</b>
  <%= @account.company_id %>
</p>

<p>
  <b>Data de vencimento:</b>
  <%= @account.due_date %>
</p> -->
<p>
  <b>Fornecedor:</b>
  <%= @account.supplier.name %>
</p>

<p>
  <b>Centro de custo:</b>
  <%= @account.company && @account.company.name %>
</p>

<p>
  <b>Vencimento:</b>
  <%= @account.due_date_br %>
</p>

<p>
  <b>Descritivo:</b>
  <%= @account.description %>
</p>

<p>
  <b>Valor:</b>
  <%= @account.value.real %>
</p>

<p>
  <b>Deconto:</b>
  <%= @account.discount.real %>
</p>

<p>
  <b>Juros:</b>
  <%= @account.interest.real %>
</p>

<p>
  <b>Valor final:</b>
  <%= @account.total.real %>
</p>

<p>
  <b>Código de barras:</b>
  <%= @account.barcode %>
</p>

<p>
  <b>Pago:</b>
  <%= @account.payed ? 'sim' : 'não' %>
</p>

<p>
  <b>Data de pagamento:</b>
  <%= @account.payment_date_br %>
</p>

<%= link_to image_tag("edit.png", :size=>"40x40", :border=>0, :title=>"Editar"), edit_account_path(@account) %>